# Copyright (c) 2021 Peachlab. All Rights Reserved.
# Author  : goat.zhou@qq.com (Yang Zhou)

package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'voice-activity-detection',
    srcs = [
        'voice-activity-detection.cc',
    ],
    hdrs = ['voice-activity-detection.h'],
    deps = [
        "//base:kaldi-base",
        "//matrix:kaldi-matrix",
        "//util:kaldi-util",
    ],
)
