# Copyright (c) 2020 PeachLab. All Rights Reserved.
# Author : goat.zhou@qq.com (Yang Zhou)

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "hello_gtest",
    srcs = [
        "hello_gtest.cc",
    ],
		hdrs = [
		    "hello_gtest.h",
		],
    deps = [
        "@com_google_googletest//:gtest",
    ],
)

